services:
  
  db:
    image: postgres:16.3
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hospitaldb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    container_name: postgres_adminer
    ports:
      - 8080:8080

volumes:
  pgdata: 